name: Deploy NestJS to Droplet

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH
      
    - name: Install dependencies
      run: bun install

    - name: Build app
      run: bun run build

    - name: Run NestJS server
      run: |
        pm2 delete nest-app || true
        pm2 start dist/main.js --name nest-app
